# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Geek Projekt
email: vijay@thegeekprojekt.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there! I'm Vijay Tholpadi, software programmer with most of my work on iOS development. I have worked on applications with a strong focus on indoor/outdoor location based services. I also have experience building applications for print-media houses. Check out my portfoilio for more info.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thegeekprojekt.com" # the base hostname & protocol for your site
twitter_username: vijaytholpadi
github_username:  vijaytholpadi

# Build settings
markdown: kramdown
